using System;

namespace AIChara;

public static class ChaListDefine
{
	public enum CategoryNo
	{
		unknown = -1,
		cha_sample_m = 0,
		cha_sample_f = 1,
		init_mind_param = 3,
		cha_sample_voice = 5,
		mole_layout = 6,
		facepaint_layout = 7,
		bodypaint_layout = 8,
		mo_head = 110,
		mt_skin_f = 111,
		mt_detail_f = 112,
		mt_beard = 121,
		mt_skin_b = 131,
		mt_detail_b = 132,
		mt_sunburn = 133,
		mo_top = 140,
		mo_bot = 141,
		mo_gloves = 144,
		mo_shoes = 147,
		fo_head = 210,
		ft_skin_f = 211,
		ft_detail_f = 212,
		ft_skin_b = 231,
		ft_detail_b = 232,
		ft_sunburn = 233,
		fo_top = 240,
		fo_bot = 241,
		fo_inner_t = 242,
		fo_inner_b = 243,
		fo_gloves = 244,
		fo_panst = 245,
		fo_socks = 246,
		fo_shoes = 247,
		so_hair_b = 300,
		so_hair_f = 301,
		so_hair_s = 302,
		so_hair_o = 303,
		preset_hair_color = 305,
		st_hairmeshptn = 306,
		st_paint = 313,
		st_eyebrow = 314,
		st_eyelash = 315,
		st_eyeshadow = 316,
		st_eye = 317,
		st_eyeblack = 318,
		st_eye_hl = 319,
		st_cheek = 320,
		st_lip = 322,
		st_mole = 323,
		st_nip = 334,
		st_underhair = 335,
		preset_skin_color = 336,
		st_pattern = 348,
		ao_none = 350,
		ao_head = 351,
		ao_ear = 352,
		ao_glasses = 353,
		ao_face = 354,
		ao_neck = 355,
		ao_shoulder = 356,
		ao_chest = 357,
		ao_waist = 358,
		ao_back = 359,
		ao_arm = 360,
		ao_hand = 361,
		ao_leg = 362,
		ao_kokan = 363,
		custom_pose_m = 500,
		custom_pose_f = 501,
		custom_eyebrow_m = 502,
		custom_eyebrow_f = 503,
		custom_eye_m = 504,
		custom_eye_f = 505,
		custom_mouth_m = 506,
		custom_mouth_f = 507
	}

	public enum KeyType
	{
		Unknown = -1,
		ListIndex,
		Category,
		DistributionNo,
		ID,
		Kind,
		Possess,
		Name,
		EN_US,
		ZH_CN,
		ZH_TW,
		JA_JP_PT,
		EN_US_PT,
		ZH_CN_PT,
		ZH_TW_PT,
		MainManifest,
		MainAB,
		MainData,
		MainData02,
		Weights,
		RingOff,
		AddScale,
		AddTex,
		CenterScale,
		CenterX,
		CenterY,
		ColorMask02Tex,
		ColorMask03Tex,
		ColorMaskTex,
		Coordinate,
		Data01,
		Data02,
		Data03,
		Eye01,
		Eye02,
		Eye03,
		EyeMax01,
		EyeMax02,
		EyeMax03,
		Eyebrow01,
		Eyebrow02,
		Eyebrow03,
		EyeHiLight01,
		EyeHiLight02,
		EyeHiLight03,
		GlossTex,
		HeadID,
		KokanHide,
		MainTex,
		MainTex02,
		MainTex03,
		MainTexAB,
		MatData,
		Mouth01,
		Mouth02,
		Mouth03,
		MouthMax01,
		MouthMax02,
		MouthMax03,
		MoveX,
		MoveY,
		NormalMapTex,
		NotBra,
		OcclusionMapTex,
		OverBodyMask,
		OverBodyMaskAB,
		OverBraMask,
		OverBraMaskAB,
		BreakDisableMask,
		OverInnerTBMask,
		OverInnerTBMaskAB,
		OverInnerBMask,
		OverInnerBMaskAB,
		OverPanstMask,
		OverPanstMaskAB,
		OverBodyBMask,
		OverBodyBMaskAB,
		Parent,
		PosX,
		PosY,
		Preset,
		Rot,
		Scale,
		SetHair,
		ShapeAnime,
		StateType,
		ThumbAB,
		ThumbTex,
		Clip,
		OverBraType,
		Pattern,
		Target,
		Correct,
		TexManifest,
		TexAB,
		TexD,
		TexC,
		FAVOR,
		ENJOYMENT,
		AVERSION,
		SLAVERY,
		SampleH,
		SampleS,
		SampleV,
		TopH,
		TopS,
		TopV,
		BaseH,
		BaseS,
		BaseV,
		UnderH,
		UnderS,
		UnderV,
		SpecularH,
		SpecularS,
		SpecularV,
		Metallic,
		Smoothness,
		IKAB,
		IKData
	}

	public static readonly Version CheckItemVersion = new Version("0.0.0");

	public static readonly string CheckItemFile = "save/checkitem.dat";

	public static string GetCategoryName(int no)
	{
		return no switch
		{
			0 => "キャラサンプル男", 
			1 => "キャラサンプル女", 
			3 => "心情による初期補正値", 
			5 => "サンプル音声", 
			6 => "ホクロの配置設定", 
			7 => "フェイスペイントの配置設定", 
			8 => "ボディーペイントの配置設定", 
			110 => "男頭", 
			111 => "男肌", 
			112 => "男シワ", 
			121 => "男ヒゲ", 
			131 => "男肌", 
			132 => "男肉感", 
			133 => "男日焼け", 
			140 => "男服上", 
			141 => "男服下", 
			144 => "男手袋", 
			147 => "男靴", 
			210 => "女頭", 
			211 => "女肌", 
			212 => "女シワ", 
			231 => "女肌", 
			232 => "女肉感", 
			233 => "女日焼け", 
			240 => "女服上", 
			241 => "女服下", 
			242 => "女インナー上", 
			243 => "女インナー下", 
			244 => "女手袋", 
			245 => "女パンスト", 
			246 => "女靴下", 
			247 => "女靴", 
			300 => "後ろ髪", 
			301 => "前髪", 
			302 => "横髪", 
			303 => "エクステ", 
			305 => "髪の毛のカラープリセット", 
			306 => "髪メッシュパターン", 
			313 => "ペイント顔・体", 
			314 => "眉毛", 
			315 => "睫毛", 
			316 => "アイシャドウ", 
			317 => "瞳", 
			318 => "瞳孔", 
			319 => "ハイライト", 
			320 => "チーク", 
			322 => "リップ", 
			323 => "ホクロ", 
			334 => "乳首", 
			335 => "アンダーヘア", 
			336 => "肌のカラープリセット", 
			348 => "パターンテクスチャ", 
			350 => "アクセサリ(なし)", 
			351 => "アクセサリ頭", 
			352 => "アクセサリ耳", 
			353 => "アクセサリ眼鏡", 
			354 => "アクセサリ顔", 
			355 => "アクセサリ首", 
			356 => "アクセサリ肩", 
			357 => "アクセサリ胸", 
			358 => "アクセサリ腰", 
			359 => "アクセサリ背中", 
			360 => "アクセサリ腕", 
			361 => "アクセサリ手", 
			362 => "アクセサリ脚", 
			363 => "アクセサリ股間", 
			500 => "カスタム男ポーズ", 
			501 => "カスタム女ポーズ", 
			502 => "カスタム男眉パターン", 
			503 => "カスタム女眉パターン", 
			504 => "カスタム男目パターン", 
			505 => "カスタム女目パターン", 
			506 => "カスタム男口パターン", 
			507 => "カスタム女口パターン", 
			_ => "", 
		};
	}
}
